export declare const gNewRequestConversationId = "_$uikit_new_request_id";
export declare const gNewRequestConversationUserId = "_$uikit_new_request_user_id";
export declare const gNewRequestConversationUserName = "_$uikit_new_request_user_name";
export declare const gNewRequestConversationUserAvatar = "_$uikit_new_request_user_avatar";
export declare const gNewRequestConversationTip = "_$uikit_new_request_tip";
export declare const gNewRequestConversationState = "_$uikit_new_request_state";
export declare const gNewRequestConversationMsgEventType = "_$uikit_new_request_event";
export declare const gGroupMemberMyRemark = "chatUIKit_group_member_nick_name";
export declare const gConversationSystemMessage = "_$uikit_conv_system_msg";
export declare const gCustomMessageCardEventType = "userCard";
export declare const gCustomMessageRecallEventType = "_$uikit_msg_recall";
export declare const gCustomMessageCreateGroupEventType = "_$uikit_create_group";
export declare const gMessageAttributeQuote = "msgQuote";
export declare const gMessageAttributeUserInfo = "ease_chat_uikit_user_info";
export declare const gMessageAttributeVoiceReadFlag = "_$uikit_voice_read_flag";
export declare const gMessageAttributeFileProgress = "_$uikit_file_progress";
export declare const gMessageAttributeMentions = "em_at_list";
//# sourceMappingURL=const.d.ts.map