"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.release_area = exports.language = void 0;
// This file is automatically generated. The user needs to manually fill in the necessary parameters.

const language = 'zh-Hans'; // 'en' or 'zh-Hans'
exports.language = language;
const release_area = 'china'; // 'china' or 'global'
exports.release_area = release_area;
//# sourceMappingURL=config.local.js.map