import * as React from 'react';
import type { AlertRef } from '../../ui/Alert';
import type { SimpleToastRef } from '../../ui/Toast';
import type { BottomSheetNameMenuRef } from '../BottomSheetMenu';
import type { GroupInfoProps, GroupInfoRef } from './types';
export declare function useGroupInfo(props: GroupInfoProps, ref?: React.ForwardedRef<GroupInfoRef>): {
    doNotDisturb: boolean | undefined;
    onDoNotDisturb: (value: boolean) => void;
    onClearChat: () => void;
    groupName: string | undefined;
    onGroupName: () => void;
    groupAvatar: string | undefined;
    onGroupAvatar: (_newGroupAvatar: string) => void;
    groupDescription: string | undefined;
    onGroupDescription: () => void;
    onGroupMyRemark: () => void;
    alertRef: React.MutableRefObject<AlertRef>;
    toastRef: React.MutableRefObject<SimpleToastRef>;
    onCopyId: () => void;
    onParticipant: () => void;
    onRequestCloseMenu: () => void;
    menuRef: React.MutableRefObject<BottomSheetNameMenuRef>;
    onMore: () => void;
    groupMemberCount: number;
    isOwner: boolean;
    tr: (key: string, ...args: any[]) => string;
    onAudioCall: () => void;
    onVideoCall: () => void;
    onSendMessage: () => void;
    onBack?: ((data?: any) => void) | undefined;
    navigationBarVisible?: boolean | undefined;
    customNavigationBar?: React.ReactElement<any, string | React.JSXElementConstructor<any>> | undefined;
    onClickedNavigationBarButton?: (() => void) | undefined;
    hasSendMessage?: boolean | undefined;
    hasAudioCall?: boolean | undefined;
    hasVideoCall?: boolean | undefined;
    containerStyle?: import("react-native/types").StyleProp<import("react-native/types").ViewStyle>;
    onInitMenu?: ((initItems: import("../BottomSheetMenu").InitMenuItemsType[]) => import("../BottomSheetMenu").InitMenuItemsType[]) | undefined;
    onInitButton?: ((initButtons: React.ReactElement<import("../..").BlockButtonProps, string | React.JSXElementConstructor<any>>[]) => React.ReactElement<import("../..").BlockButtonProps, string | React.JSXElementConstructor<any>>[]) | undefined;
    groupId: string;
    ownerId?: string | undefined;
    groupMyRemark?: string | undefined;
    onClickedChangeGroupOwner?: ((groupId: string, ownerId: string) => void) | undefined;
    onGroupDestroy?: ((groupId: string) => void) | undefined;
    onGroupQuit?: ((groupId: string) => void) | undefined;
    onGroupKicked?: ((groupId: string) => void) | undefined;
};
//# sourceMappingURL=GroupInfo.hooks.d.ts.map