import * as React from 'react';
import type { AlertRef } from '../../ui/Alert';
import type { SimpleToastRef } from '../../ui/Toast';
import type { BottomSheetNameMenuRef } from '../BottomSheetMenu';
import type { GroupParticipantInfoProps } from './types';
export declare function useGroupParticipantInfo(props: GroupParticipantInfoProps): {
    doNotDisturb: boolean | undefined;
    onDoNotDisturb: (value: boolean) => void;
    onClearChat: () => void;
    alertRef: React.MutableRefObject<AlertRef>;
    userName: string | undefined;
    userAvatar: string | undefined;
    userRemark: string | undefined;
    onCopyId: () => void;
    toastRef: React.MutableRefObject<SimpleToastRef>;
    onRemark: () => void;
    isContact: boolean | undefined;
    tr: (key: string, ...args: any[]) => string;
    onAddContact: () => void;
    onSendMessage: () => void;
    onVideoCall: () => void;
    onAudioCall: () => void;
    isSelf: boolean;
    onRequestCloseMenu: (onFinished?: (() => void) | undefined) => void;
    menuRef: React.MutableRefObject<BottomSheetNameMenuRef>;
    onBack?: ((data?: any) => void) | undefined;
    navigationBarVisible?: boolean | undefined;
    customNavigationBar?: React.ReactElement<any, string | React.JSXElementConstructor<any>> | undefined;
    onClickedNavigationBarButton?: (() => void) | undefined;
    hasSendMessage?: boolean | undefined;
    hasAudioCall?: boolean | undefined;
    hasVideoCall?: boolean | undefined;
    containerStyle?: import("react-native/types").StyleProp<import("react-native/types").ViewStyle>;
    onInitMenu?: ((initItems: import("../BottomSheetMenu").InitMenuItemsType[]) => import("../BottomSheetMenu").InitMenuItemsType[]) | undefined;
    onInitButton?: ((initButtons: React.ReactElement<import("../..").BlockButtonProps, string | React.JSXElementConstructor<any>>[]) => React.ReactElement<import("../..").BlockButtonProps, string | React.JSXElementConstructor<any>>[]) | undefined;
    userId: string;
    groupId: string;
    onGroupParticipantRemark?: ((groupId: string, memberId: string) => void) | undefined;
};
//# sourceMappingURL=GroupParticipantInfo.hooks.d.ts.map