// This file is automatically generated. The user needs to manually fill in the necessary parameters.

export const language = 'zh-Hans'; // 'en' or 'zh-Hans'
export const release_area = 'china'; // 'china' or 'global'
//# sourceMappingURL=config.local.js.map