import * as React from 'react';
import type { AvatarViewProps, CheckViewProps, MessageBubbleProps, MessageContentProps, MessageCustomCardProps, MessageDefaultImageProps, MessageFileProps, MessageImageProps, MessageQuoteBubbleProps, MessageTextProps, MessageVideoProps, MessageViewProps, MessageVoiceProps, NameViewProps, StateViewProps, SystemTipViewProps, TimeTipViewProps, TimeViewProps } from './MessageListItem.type';
import type { MessageListItemProps } from './types';
export declare function MessageText(props: MessageTextProps): JSX.Element;
export declare function MessageDefaultImage(props: MessageDefaultImageProps): JSX.Element;
export declare function MessageImage(props: MessageImageProps): JSX.Element;
export declare function MessageVoice(props: MessageVoiceProps): JSX.Element;
export declare function MessageVideo(props: MessageVideoProps): JSX.Element;
export declare function MessageFile(props: MessageFileProps): JSX.Element;
export declare function MessageCustomCard(props: MessageCustomCardProps): JSX.Element;
export declare function MessageContent(props: MessageContentProps): JSX.Element;
export declare function MessageBubble(props: MessageBubbleProps): JSX.Element;
export declare function AvatarView(props: AvatarViewProps): JSX.Element;
export declare function NameView(props: NameViewProps): JSX.Element;
export declare function TimeView(props: TimeViewProps): JSX.Element;
export declare function StateView(props: StateViewProps): JSX.Element;
export declare function CheckView(props: CheckViewProps): JSX.Element;
export declare function MessageQuoteBubble(props: MessageQuoteBubbleProps): JSX.Element;
export declare function MessageView(props: MessageViewProps): JSX.Element;
export declare function SystemTipView(props: SystemTipViewProps): JSX.Element;
export declare function TimeTipView(props: TimeTipViewProps): JSX.Element;
export declare function MessageListItem(props: MessageListItemProps): JSX.Element;
export declare const MessageListItemMemo: React.MemoExoticComponent<typeof MessageListItem>;
//# sourceMappingURL=MessageListItem.d.ts.map